spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 920551120026-0k90vj5li039ut6536gd911op9q8rpc8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: ptAfyD4K7h8mTses1X0C
            client-secret: MZnOecq4qc
            client-authentication-method: post
            redirect-uri:  http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - nickname
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response